version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: "host"
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    build: .
    network_mode: "host"
    ports:
        - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 19092
      KAFKA_CREATE_TOPICS: "rwo:1:1,rgr:1:1,mpr:2:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
    volumes:
        - /var/run/docker.sock:/var/run/docker.sdockerock

  kafka-2:
    build: .
    network_mode: "host"    
    ports:
        - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_PORT: 29092
      KAFKA_CREATE_TOPICS: "rwo:1:1,rgr:1:1,mpr:2:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  kafka-3:
    build: .
    network_mode: "host"
    ports:
        - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_PORT: 39092
      KAFKA_CREATE_TOPICS: "rwo:1:1,rgr:1:1,mpr:2:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
